/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as SettingsAdminRouteImport } from './routes/settings.admin'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAdminRoute = SettingsAdminRouteImport.update({
  id: '/settings/admin',
  path: '/settings/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/artifacts': typeof ArtifactsRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/datasets': typeof DatasetsRoute
  '/docs': typeof DocsRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/runs': typeof RunsRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/team': typeof TeamRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/settings/admin': typeof SettingsAdminRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/artifacts': typeof ArtifactsRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/datasets': typeof DatasetsRoute
  '/docs': typeof DocsRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/runs': typeof RunsRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/team': typeof TeamRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/settings/admin': typeof SettingsAdminRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/artifacts': typeof ArtifactsRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/datasets': typeof DatasetsRoute
  '/docs': typeof DocsRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/runs': typeof RunsRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/team': typeof TeamRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/settings/admin': typeof SettingsAdminRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/artifacts'
    | '/changelog'
    | '/dashboard'
    | '/datasets'
    | '/docs'
    | '/jobs'
    | '/login'
    | '/models'
    | '/notifications'
    | '/pricing'
    | '/privacy-policy'
    | '/runs'
    | '/signup'
    | '/status'
    | '/team'
    | '/terms-of-service'
    | '/settings/admin'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/profile'
    | '/settings/security'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/artifacts'
    | '/changelog'
    | '/dashboard'
    | '/datasets'
    | '/docs'
    | '/jobs'
    | '/login'
    | '/models'
    | '/notifications'
    | '/pricing'
    | '/privacy-policy'
    | '/runs'
    | '/signup'
    | '/status'
    | '/team'
    | '/terms-of-service'
    | '/settings/admin'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/profile'
    | '/settings/security'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/artifacts'
    | '/changelog'
    | '/dashboard'
    | '/datasets'
    | '/docs'
    | '/jobs'
    | '/login'
    | '/models'
    | '/notifications'
    | '/pricing'
    | '/privacy-policy'
    | '/runs'
    | '/signup'
    | '/status'
    | '/team'
    | '/terms-of-service'
    | '/settings/admin'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/profile'
    | '/settings/security'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  ArtifactsRoute: typeof ArtifactsRoute
  ChangelogRoute: typeof ChangelogRoute
  DashboardRoute: typeof DashboardRoute
  DatasetsRoute: typeof DatasetsRoute
  DocsRoute: typeof DocsRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  ModelsRoute: typeof ModelsRoute
  NotificationsRoute: typeof NotificationsRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RunsRoute: typeof RunsRoute
  SignupRoute: typeof SignupRoute
  StatusRoute: typeof StatusRoute
  TeamRoute: typeof TeamRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  SettingsAdminRoute: typeof SettingsAdminRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/admin': {
      id: '/settings/admin'
      path: '/settings/admin'
      fullPath: '/settings/admin'
      preLoaderRoute: typeof SettingsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  ArtifactsRoute: ArtifactsRoute,
  ChangelogRoute: ChangelogRoute,
  DashboardRoute: DashboardRoute,
  DatasetsRoute: DatasetsRoute,
  DocsRoute: DocsRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  ModelsRoute: ModelsRoute,
  NotificationsRoute: NotificationsRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RunsRoute: RunsRoute,
  SignupRoute: SignupRoute,
  StatusRoute: StatusRoute,
  TeamRoute: TeamRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  SettingsAdminRoute: SettingsAdminRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
