"""
Adds /root/.config/neuro/config.yaml to the Cowrie fs.pickle with full
canarytoken credentials. Handles both string and bytes name encoding.
Run inside the Cowrie container from /cowrie/var/log/cowrie/.
"""
import pickle, time

A_NAME=0; A_TYPE=1; A_UID=2; A_GID=3; A_SIZE=4; A_MODE=5; A_CTIME=6; A_CONTENTS=7; A_TARGET=8; A_REALFILE=9
T_LINK=0; T_DIR=1; T_FILE=2

PICKLE_PATH = '/cowrie/cowrie-git/src/cowrie/data/fs.pickle'
OUT_PATH    = '/cowrie/var/log/cowrie/fs.pickle'

CONTENT = b"""# Neuro platform config -- neuro-train-01
# Generated by deploy/scripts/gen-config.sh -- DO NOT COMMIT
environment: production

database:
  host: 10.0.0.5
  port: 3306
  name: neuro_prod
  user: neuro_app
  password: IPMCRyPKQbooGAo9XFvaNGbimqbmSaB1xoKwuUneY

redis:
  host: 10.0.0.6
  port: 6379

aws:
  access_key_id: AKIAYZM57LXRGIYTCOUV
  secret_access_key: "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"
  region: us-east-1
  s3_bucket: neuro-ml-artifacts

monitoring:
  wandb_api_key: a4f7c2e1b8d3905f6a71c2e4d0b93a7f58124e6d
  openai_api_key: sk-proj-p8Kz2mRvN4wL9jT7bYcDxQ3aF6sE1hU5nM0qW8dP
"""

def name_eq(a, b):
    """Compare names regardless of bytes/str encoding."""
    a = a.decode() if isinstance(a, bytes) else a
    b = b.decode() if isinstance(b, bytes) else b
    return a == b

def find_child(contents, name, typ):
    for child in contents:
        if isinstance(child, list) and child[A_TYPE] == typ and name_eq(child[A_NAME], name):
            return child
    return None

def ensure_dir(contents, name):
    existing = find_child(contents, name, T_DIR)
    if existing:
        print(f'  dir exists: {name}')
        return existing
    # Use same encoding as existing entries
    enc = name.encode() if contents and isinstance(contents[0][A_NAME], bytes) else name
    new_dir = [enc, T_DIR, 0, 0, 4096, 0o40755, time.time(), [], b'', b'']
    contents.append(new_dir)
    print(f'  created dir: {name}')
    return new_dir

with open(PICKLE_PATH, 'rb') as f:
    fs = pickle.load(f)

root_contents = fs[A_CONTENTS]

# Navigate to /root
root_dir = find_child(root_contents, 'root', T_DIR)
if not root_dir:
    print('ERROR: /root not found. Available:', [
        (c[A_NAME] if isinstance(c, list) else '?') for c in root_contents[:10]
    ])
    raise SystemExit(1)
print('Found /root')

config_dir = ensure_dir(root_dir[A_CONTENTS], '.config')
neuro_dir  = ensure_dir(config_dir[A_CONTENTS], 'neuro')

# Determine name encoding from sibling entries
sample = neuro_dir[A_CONTENTS]
use_bytes = sample and isinstance(sample[0][A_NAME], bytes) if sample else True
fname = b'config.yaml' if use_bytes else 'config.yaml'

existing = find_child(neuro_dir[A_CONTENTS], 'config.yaml', T_FILE)
if existing:
    print('config.yaml exists — updating')
    existing[A_CONTENTS] = CONTENT
    existing[A_SIZE]     = len(CONTENT)
    existing[A_CTIME]    = time.time()
else:
    print('config.yaml missing — adding')
    neuro_dir[A_CONTENTS].append(
        [fname, T_FILE, 0, 0, len(CONTENT), 0o100644, time.time(), CONTENT, b'', b'']
    )

# Also patch .bash_history if present
hist = find_child(root_dir[A_CONTENTS], '.bash_history', T_FILE)
if hist and isinstance(hist[A_CONTENTS], bytes):
    h = hist[A_CONTENTS]
    h = h.replace(b'AKIAQF3ZXVN2MPLR8KT4', b'AKIAYZM57LXRGIYTCOUV')
    h = h.replace(b'gX7vL2mR9nK4wP8qY3jT6bZcF1sE0hA5uN2dW7eK', b'MpTqbycbuKX0q40aU5yCwCNtS2rWCzzH4cko/ptU')
    hist[A_CONTENTS] = h
    hist[A_SIZE] = len(h)
    print('Updated .bash_history')

with open(OUT_PATH, 'wb') as f:
    pickle.dump(fs, f)
print(f'Saved to {OUT_PATH} — done.')
